/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rocco, Suchana, Cheliyan
 */
public class EnemySelectionScreen extends javax.swing.JFrame {

    /**
     * Creates new form PixelHeroMenu
     */
    public EnemySelectionScreen() {
        initComponents();
        setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBackPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnKnight = new javax.swing.JButton();
        btnRagnarok = new javax.swing.JButton();
        btnFireDemon = new javax.swing.JButton();
        lblKnight = new javax.swing.JLabel();
        lblRagnarok = new javax.swing.JLabel();
        lblFireDemon = new javax.swing.JLabel();
        lblBeginner = new javax.swing.JLabel();
        lblExperienced = new javax.swing.JLabel();
        lblAdvanced = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        menuBackPanel.setBackground(new java.awt.Color(153, 204, 255));
        menuBackPanel.setPreferredSize(new java.awt.Dimension(1000, 720));
        menuBackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        lblTitle.setText("Choose Your Oppenent");
        menuBackPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btnKnight.setBackground(new java.awt.Color(255, 204, 102));
        btnKnight.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnKnight.setText("Knight");
        btnKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnightActionPerformed(evt);
            }
        });
        menuBackPanel.add(btnKnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 300, -1));

        btnRagnarok.setBackground(new java.awt.Color(255, 204, 102));
        btnRagnarok.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnRagnarok.setText("Ragnarok");
        btnRagnarok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRagnarokActionPerformed(evt);
            }
        });
        menuBackPanel.add(btnRagnarok, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 300, -1));

        btnFireDemon.setBackground(new java.awt.Color(255, 204, 102));
        btnFireDemon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnFireDemon.setText("Fire Demon");
        btnFireDemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFireDemonActionPerformed(evt);
            }
        });
        menuBackPanel.add(btnFireDemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 300, -1));

        lblKnight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KnightSelectionPic.png"))); // NOI18N
        menuBackPanel.add(lblKnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 240, 230));

        lblRagnarok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RagnarokSelection.png"))); // NOI18N
        menuBackPanel.add(lblRagnarok, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 240, 250));

        lblFireDemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FireDemonSelectionPic.png"))); // NOI18N
        menuBackPanel.add(lblFireDemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 240, 270));

        lblBeginner.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBeginner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBeginner.setText("(Beginner)");
        menuBackPanel.add(lblBeginner, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, -1));

        lblExperienced.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblExperienced.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExperienced.setText("(Experienced)");
        menuBackPanel.add(lblExperienced, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, -1, -1));

        lblAdvanced.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblAdvanced.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdvanced.setText("(Advanced)");
        menuBackPanel.add(lblAdvanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBackPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBackPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFireDemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFireDemonActionPerformed
        //Switiching to the fire demon's level
        new BattleLevel3().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFireDemonActionPerformed

    private void btnKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnightActionPerformed
        //Switching to the knight's level
        new BattleLevel1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKnightActionPerformed

    private void btnRagnarokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRagnarokActionPerformed
        //Switching to ragnarok's level
        new BattleLevel2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRagnarokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnemySelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnemySelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnemySelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnemySelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnemySelectionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFireDemon;
    private javax.swing.JButton btnKnight;
    private javax.swing.JButton btnRagnarok;
    private javax.swing.JLabel lblAdvanced;
    private javax.swing.JLabel lblBeginner;
    private javax.swing.JLabel lblExperienced;
    private javax.swing.JLabel lblFireDemon;
    private javax.swing.JLabel lblKnight;
    private javax.swing.JLabel lblRagnarok;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel menuBackPanel;
    // End of variables declaration//GEN-END:variables
}
